source 'https://rubygems.org'

ruby '~> 3.0'

gem 'sinatra', '~> 4.0'
gem 'json', '~> 2.6'
gem 'rackup', '~> 2.1'
gem 'puma', '~> 6.0'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'rspec-parameterized', '~> 1.0'
end